### PR TITLE
Fix install issues, streamline process

### PR DESCRIPTION
**Pull request by Zackptg5**
There's really no need for any of the variables, using the inverse logic turns out to be much easier in this case

### CODE REVIEW

**Comment by MarcAnt01** [comment]
Your modifications seem to cause bootloop, I think it's because of the stuff being copied to /system instead of /product

**Comment by Zackptg5** [comment]
Oh, it's supposed to be product? Missed that. Just move everything to system/product and update the paths in install.sh
The principle is to delete what's not being used

**Comment by MarcAnt01** [comment]
> Oh, it's supposed to be product? Missed that. Just move everything to system/product and update the paths in install.sh
> The principle is to delete what's not being used

The thing is that I have to copy to product only if the folder exists, otherwise just to system; that's why I have made a separated folders to copy all the stuff manually.

**Comment by Zackptg5** [comment]
Pushed product fix so that should be covered now

**Review by MarcAnt01 — CHANGES_REQUESTED** [review]
Product in not only $ORIGDIR/product, but can be also $ORIGDIR/system/product in some devices like mine

**Comment by MarcAnt01** [comment]
Nvm, I have found out that I can commit to branches of forks involved in prs, so fixed that by myself

**Comment by MarcAnt01** [comment]
I installed with the required changes, but still the same problems of the beginning, Gallery apk doesn't get installed

**Comment by MarcAnt01** [comment]
OK, moving to /system/(product/)app instead of priv-app did the job.

**Comment by MarcAnt01** [comment]
I would like to thank you for the effort you've put in helping me, have a good day Zack😁

**Comment by Zackptg5** [comment]
No problem :)

**Pull request merged**
